# Generated by Django 4.2.3 on 2023-08-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField(null=True)),
                ("total_num", models.IntegerField(null=True)),
                ("reject", models.IntegerField(null=True)),
                ("arrive", models.IntegerField(null=True)),
                ("reject_rating", models.FloatField(null=True)),
                ("times", models.FloatField(null=True)),
            ],
            options={
                "db_table": "statistics",
            },
        ),
    ]
