# Generated by Django 4.2.3 on 2023-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("yyzc", "0002_delete_statistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("month", models.IntegerField(primary_key=True, serialize=False)),
                ("total_num", models.IntegerField(null=True)),
                ("reject", models.IntegerField(null=True)),
                ("arrive", models.IntegerField(null=True)),
                ("reject_rating", models.FloatField(null=True)),
                ("times", models.FloatField(null=True)),
            ],
            options={
                "db_table": "statistics",
            },
        ),
    ]
